[project]
name = "melody-thoughts-blog"
version = "1.0.0"
description = "A music blog website for role-playing games"
authors = [{ name = "Role-Playing Game Creator" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.uv]
dev-dependencies = []
